name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TAG: $(date +%s)
    steps:
    - uses: actions/checkout@v3
    - name: get-date
      run: echo "set-output TAG=date::$(date +%s))"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aistream1/flow_sweep:${{ env.TAG}}
    - name: docker-login
      run: docker login -u aistream1 -p ${{ secrets.DOCKER_SEC}}
    - name: pus
      run: docker push aistream1/flow_sweep:${{ env.TAG}}
